### ISSUE TITLE
leicht irreführender Schaltplan

### ISSUE THREAD

**Issue by Stat1c-V01D** [jolau/QlockTwo_DIY#3]
Auf dem in der Repo angelegten Schaltplan wird vermittelt, dass es sich bei dem LED-Strip um WS2812b LED's handelt.
Diese LED's haben aber keinen weißen Channel und sind auch nicht zur Verwendung mit dem gegebenen Sourcecode geeignet.
Die richtige Art an LED Strips wäre SK6812 wenn man bei 5V bleiben will.

**Comment by jolau** [comment]
You're right. Please create a pull request with the fixed schematics. Thanks!
