### ISSUE TITLE
Question about font choice

### ISSUE THREAD

**Issue by LeslieGoldsmith** [jolau/QlockTwo_DIY#5]
Thank you very much for the material and ideas you've posted.

I'm wondering what font you chose, as it seems to be a very good replica as far as shape, aspect ratio, and weight are concerned. (Of course the manufacturer's customizations to letters with enclosures are not present.)

A font that I have found that is fairly close is DIN Next Arabic Regular. What did you use?

**Comment by jolau** [comment]
We've used the FF DIN Light font. I'm not sure where we've got it, but maybe it could be this one: https://fontsgeek.com/fonts/din-light

**Comment by LeslieGoldsmith** [comment]
Thanks for the quick response!
