### ISSUE TITLE
Estimated overall costs

### ISSUE THREAD

**Issue by peterkaosa** [jolau/QlockTwo_DIY#6]
Hi, what a great idea to share this clock! I am currently planning on building one for my family. Will take it to our local openlab as I guess they are pretty well equipped and will help me throughout the building process. Can you tell us a rough estimation of costs for the mere parts one has to buy? I am asking for typical german costs...

**Comment by fletsch** [comment]
Hi, thanks for your interest in our project! Costs for the hardware were around `CHF 160` for one clock. The biggest part was for the acrylic panel (around `CHF 60` per clock), followed by the LED stripes (around `CHF 25` per clock) and then everything adds up (electronic parts, wood, colour, magnets...). Note that we built a batch of 5 clocks which might have affected the costs and we had free access to laser cutter, CNC mill and a well equipped electronics workshop.
